#Numpy assignment

In [26]:
import numpy as np
list_ = [ "1" , "2" , "3" , "4" , "5" ]
array_list = np.array(object = list_ ,dtype=int)
array_list

array([1, 2, 3, 4, 5])

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [4]:
list_

['1', '2', '3', '4', '5']

In [9]:
dtype1=type(list_)
print("Data type of variable list : ", dtype1)

Data type of variable list :  <class 'list'>


In [10]:
data2=type(array_list)
print("Data type of varaible array_list : ", data2)

Data type of varaible array_list :  <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [30]:
def dtypes(x):
    for i in list_:
        
        print(type(list_))

print("\nData of each and every elements of list")
dtypes(2) 

def dtypes2(x):
    for i in array_list:
        print(type(array_list))
print("\nData of each and every elements of array list")     
dtypes2(3)


Data of each and every elements of list
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>

Data of each and every elements of array list
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [27]:
array_list

array([1, 2, 3, 4, 5])

In [28]:
type(array_list)

numpy.ndarray

In [31]:
def dtypes2(x):
    for i in array_list:
        print(type(array_list))
print("\nData of each and every elements of array list")     
dtypes2(3)


Data of each and every elements of array list
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [49]:
import pandas as pd

list_ = [1, 2, '3', 4.5, True]

array_list = np.array(list_, dtype=int)

def print_data_types(variable_name, data_list):
    print(f"Data types of elements in '{variable_name}':")
    for element in data_list:
        print(type(element))


print_data_types('list_', list_)


print_data_types('array_list', array_list)

Data types of elements in 'list_':
<class 'int'>
<class 'int'>
<class 'str'>
<class 'float'>
<class 'bool'>
Data types of elements in 'array_list':
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [50]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
shape=num_array.shape
print("The shape of varaible shape is : ",shape)

size=num_array.size
print("The size of varaible size is :",size)


The shape of varaible shape is :  (2, 3)
The size of varaible size is : 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [55]:

print("Here is the numpy array of 3*3 matrix containing zeroes only ")
np.zeros([3,3])

Here is the numpy array of 3*3 matrix containing zeroes only 


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [58]:
print("")
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])